import { ProductSpec } from './types';

export const products: ProductSpec[] = [
  {
    id: 1,
    name: 'Shiny Smile Veneers — Our #1 Pick',
    badge: '#1 BEST IN 2026',
    badgeStyle: 'top-pick',
    badgeColor: 'bg-green-700',
    borderColor: 'border-green-700 border-2 shadow-sm',
    imageUrl: '/images/Shiny Smile Veneers.jpg',
    features: [
      {
        label: 'Realistic look:',
        text: 'Natural shade depth and subtle translucency that blends in daylight and indoor lighting.',
        isPositive: true,
      },
      {
        label: 'Fit, comfort & hold:',
        text: 'Custom, low-profile build with smooth edges for clear speech and a secure, even grip.',
        isPositive: true,
      },
      {
        label: 'Durable finish:',
        text: 'Durable build with a stain-resistant finish for reliable everyday wear.',
        isPositive: true,
      },
      {
        label: 'Everyday usability:',
        text: 'Designed for day-to-day wear, including sensible eating.',
        isPositive: true,
      },
      {
        label: 'Quick turnaround:',
        text: 'As fast as ~2 weeks from approved impressions.',
        isPositive: true,
      },
      {
        label: 'Clear guidance:',
        text: 'Step-by-step impression support reduces do-overs.',
        isPositive: true,
      },
      {
        label: 'Remake safety net:',
        text: 'Up to three free remakes if fit or finish needs tweaks.',
        isPositive: true,
      },
      {
        label: 'Flexible payments:',
        text: 'Installments/financing ease the upfront cost.',
        isPositive: true,
      },
      {
        label: 'Best value in class:',
        text: 'With 40% off and a 60-day money-back guarantee, it’s nearly risk-free.',
        isPositive: true,
      },
      {
        label: 'Long protection:',
        text: '3-year warranty for lasting peace of mind.',
        isPositive: true,
      },
      {
        label: 'High demand:',
        text: 'Limited-time discount, often sells out quickly.',
        isPositive: false,
      },
    ],
    score: '9.9',
    ratingText: 'Excellent',
    ratingColor: 'text-green-700',
    starCount: 5,
    reviewCount: '13,518',
    discountText: '40% OFF',
    discountEnds: 'May 24, 2026',
    buttonText: 'VISIT SITE',
    link: 'https://go.consumerskills.org/click',
  },
  {
    id: 2,
    name: 'Pop On Veneers',
    badge: '#2',
    badgeStyle: 'standard',
    borderColor: 'border-gray-200',
    imageUrl: '/images/popon.jpg',
    features: [
      { text: 'Accessible pricing path: Broad installment options.', isPositive: true },
      { text: 'Fit support: Up to two remakes if fit isn’t right.', isPositive: true },
      { text: 'Easy onboarding: Clear kit instructions and care tips.', isPositive: true },
      { text: 'Shade options: Multiple shades to match different goals.', isPositive: true },
      { text: 'Self-service tools: Online forms simplify remake requests.', isPositive: true },
      { text: 'Solid starter choice: Practical entry point for first-timers.', isPositive: true },
      { label: 'Shorter coverage:', text: '30-day warranty trails our #1 pick.', isPositive: false },
      { label: 'Food limits:', text: 'Avoid hard/sticky foods and very hot drinks while wearing.', isPositive: false },
      { label: 'Process rules:', text: 'Returns/remakes must follow specific procedures; fees may apply.', isPositive: false },
      { label: 'Durability varies:', text: 'Heavy chewing shortens lifespan.', isPositive: false },
    ],
    score: '9.3',
    ratingText: 'Good',
    ratingColor: 'text-green-700',
    starCount: 4,
    reviewCount: '9,751',
    buttonText: 'VISIT SITE',
    link: 'https://amzn.to/4dK9gU0',
  },
  {
    id: 3,
    name: 'TruSmile Veneers',
    badge: '#3',
    badgeStyle: 'standard',
    borderColor: 'border-gray-200',
    imageUrl: '/images/trusmile.jpg',
    features: [
      { text: 'Fracture coverage: 120-day warranty plus a fit remake option.', isPositive: true },
      { text: 'Speed choice: Express production (~2 weeks) available for a fee.', isPositive: true },
      { text: 'Budget-friendly: Straightforward, value-oriented offering.', isPositive: true },
      { text: 'Transparent expectations: Very clear eating guidance up front.', isPositive: true },
      { text: 'Shipping options: Standard with paid upgrades for speed.', isPositive: true },
      { text: 'Simple lineup: Easy to choose without decision overload.', isPositive: true },
      { label: 'Eating discouraged:', text: 'If you do eat, soft foods only to avoid cracks.', isPositive: false },
      { label: 'Shorter protection:', text: 'Coverage window is shorter than #1.', isPositive: false },
      { label: 'Express costs extra:', text: 'Faster production raises total price.', isPositive: false },
      { label: 'Less customization depth:', text: 'Fewer model variations/features.', isPositive: false },
    ],
    score: '8.8',
    ratingText: 'Good',
    ratingColor: 'text-green-700',
    starCount: 4,
    reviewCount: '1,358',
    buttonText: 'VISIT SITE',
    link: 'https://www.trusmileveneers.com/products/trusmile-custom-made-veneers',
  },
  {
    id: 4,
    name: 'instasmile',
    badge: '#4',
    badgeStyle: 'standard',
    borderColor: 'border-gray-200',
    imageUrl: '/images/Instasmile.jpg',
    features: [
      { text: 'Coverage options: Select lines include up to 3-year protection.', isPositive: true },
      { text: 'Tiered lineup: Slim to more robust profiles for different needs.', isPositive: true },
      { text: 'Wide availability: Ships broadly with established operations.', isPositive: true },
      { text: 'Practical wear: Eating permitted with emphasis on soft foods.', isPositive: true },
      { text: 'Faster builds: Quick-turn options on certain SKUs.', isPositive: true },
      { text: 'Care guidance: Clear instructions help extend lifespan.', isPositive: true },
      { label: 'Model-specific terms:', text: 'Warranty and features vary by line.', isPositive: false },
      { label: 'Food caveats:', text: 'Hard/chewy items are discouraged.', isPositive: false },
      { label: 'Regional differences:', text: 'Policies/timelines can differ by site/country.', isPositive: false },
      { label: 'Lifestyle limits:', text: 'Not intended for heavy bite forces or corrections.', isPositive: false },
    ],
    score: '8.5',
    ratingText: 'Good',
    ratingColor: 'text-green-700',
    starCount: 4,
    reviewCount: '5,688',
    buttonText: 'VISIT SITE',
    link: 'https://us.instasmile.com/',
  },
  {
    id: 5,
    name: 'Brighter Image Lab (PressOn Veneers)',
    badge: '#5',
    badgeStyle: 'standard',
    borderColor: 'border-gray-200',
    imageUrl: '/images/5.jpg',
    features: [
      { text: 'Upgradeable protection: 90-day standard with 2-year extended add-on.', isPositive: true },
      { text: 'Speed add-ons: Express processing available.', isPositive: true },
      { text: 'Finish options: Upgrades (e.g., glazing/finish) for camera-ready shine.', isPositive: true },
      { text: 'Knowledge base: Extensive FAQs and care resources.', isPositive: true },
      { text: 'Flexible orders: Single arch or full set.', isPositive: true },
      { label: 'Short standard term:', text: '90 days unless you add the extension.', isPositive: false },
      { label: 'Eating generally not advised:', text: 'If attempted, avoid challenging foods.', isPositive: false },
      { label: 'Care overhead:', text: 'Typically remove for sleeping; extra steps.', isPositive: false },
      { label: 'Add-on creep:', text: 'Upgrades can raise final cost quickly.', isPositive: false },
    ],
    score: '7.5',
    ratingText: 'Average',
    ratingColor: 'text-green-700',
    starCount: 3,
    reviewCount: '962',
    buttonText: 'VISIT SITE',
    link: 'https://amzn.to/4dL2ugG',
  }
];
